### PR TITLE
Added an option to filter out prereleases

### PR DESCRIPTION
**Pull request by seidnerj**
Pretty self explanatory.

### CODE REVIEW

**Comment by seidnerj** [comment]
The tests seem to be failing due to Codacy configuration in the tests’ yml.

**Comment by axelrindle** [comment]
I'm pretty busy right now, but I'll try to take a look in the next couple days.

**Comment by seidnerj** [comment]
No worries. Thx.

**Comment by axelrindle** [comment]
Please rebase your branch on the master branch, I've updated the CI workflow.

**Comment by seidnerj** [comment]
I've merged your changes so should be ready. Thx!

**Review by axelrindle — CHANGES_REQUESTED** [review]
Looks good to me, but I would call the new option `excludePrereleases` instead of `filterPrerelease`.

**Comment by seidnerj** [comment]
Sure, do you want me to change it or will you?

**Comment by axelrindle** [comment]
You can do that :smile:

**Comment by seidnerj** [comment]
No problem, will do that tomorrow! Thanks!

**Comment by seidnerj** [comment]
Done. Cheers.

**Review by axelrindle — APPROVED** [review]
Great. Thank you!

**Comment by seidnerj** [comment]
Is there a planned released that will include this change by the way? I have several projects using this. Thanks!

**Pull request merged**
